baseURL: https://yuan-ru-lin.github.io/
title: Yuan-Ru Lin
theme: mini

hasCJKLanguage: true
googleAnalytics: UA-146395889-1

social:
  twitter: https://twitter.com/YuanRuLeonLin
  github: https://github.com/Yuan-Ru-Lin

params:
  dateFormat: Jan 2 2006
  author: Yuan-Ru Lin @ yuanruleonlin@gmail.com
  bio: Research Assistant in High Energy Physics Lab, National Taiwan University
  rss: /index.xml
  math: true
  showToc: true
  enableComments: true
  enableRSS: true
  enableGoogleAnalytics: true

